### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `single-board-computer`

  - `motorola-6805`

  <br>

- **Update Description**

  `Single board computer built around the Motorola 6805 CPU`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Linked files

- Added quicklinks

- Sorted files

- Added license badge

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                            [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/6805_SBC

### CODE REVIEW

**Comment by LegalizeAdulthood** [comment]
Sorry, but I don't like the changes in this PR.  If you could explain your reasoning about why you made the changes, we can discuss them and maybe I'll take some of them but as it stands, I am going to reject this.

**Comment by ElectronicsArchiver** [comment]
- Buttons make it easier for users to navigate content
- Links allow users to find files in one click
- Titles give users a data-point to identify projects with
- Descriptions communicate a brief summary of a project
- Badges indicate secondary information that users passively take in
- Sections make content more readable / understandable
- Headlines give sections a topic
- Color makes content differentiation easier
- Different shapes communicate differing intent / use
- Tags improve SEO and help users to categorize a project

**Comment by LegalizeAdulthood** [comment]
Those are all changes you made to the markdown files, but you haven't yet explained why you moved and/or renamed files.  Still not inclined to take this as-is although I'm open to improvements to the readme in isolation.

**Comment by ElectronicsArchiver** [comment]
- Removed revision name from user manual as that is stated in it anyways, there is no other revision and it's liked anyways so the name doesn't matter.
- Sorted files for better overview / categorization.

If you only want the README changes, that is fine with me~

**Comment by ElectronicsArchiver** [comment]
Done, squashed the 3 fixes into one as well~

**Pull request closed without merging**
